# KAGGLE 

https://www.kaggle.com/competitions/amp-parkinsons-disease-progression-prediction

In [1]:
import torch
import os
import pandas as pd
import torch.optim as optim
import sklearn
from sklearn.model_selection import train_test_split
sklearn.__version__

# autoreload extension
%load_ext autoreload
%autoreload 2

In [2]:
import setup_env as su
su.setup_env()

Setup python packages...


100%|██████████| 16.1M/16.1M [00:00<00:00, 33.6MB/s]



Setup dotfiles...
Running setup.sh...


--2023-04-29 01:52:54--  https://raw.githubusercontent.com/kperkins411/dotfiles/master/setup.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1022 [text/plain]
Saving to: ‘setup.sh’

     0K                                                       100% 41.9M=0s

2023-04-29 01:52:54 (41.9 MB/s) - ‘setup.sh’ saved [1022/1022]

Cloning into '/root/.cfg'...


Changing key permissions...


rm: cannot remove '/root/.vimrc': No such file or directory
rm: cannot remove '/root/.tmux.conf': No such file or directory
rm: cannot remove '/root/.ctags': No such file or directory


In [3]:
import utils_parkinsons as ut

In [6]:
df_train_cli = pd.read_csv(ut.CFG.DATAP+"train_clinical_data.csv")
df_train_pep = pd.read_csv(ut.CFG.DATAP+"train_peptides.csv")
df_train_pro = pd.read_csv(ut.CFG.DATAP+"train_proteins.csv")

In [12]:
print(f'df_train_cli={df_train_cli.shape}, df_train_pep={df_train_pep.shape},df_train_pro={df_train_pro.shape}') 

df_train_cli=(2615, 8), df_train_pep=(981834, 6),df_train_pro=(232741, 5)


In [15]:
df_train_cli.isnull().sum()

visit_id                                  0
patient_id                                0
visit_month                               0
updrs_1                                   1
updrs_2                                   2
updrs_3                                  25
updrs_4                                1038
upd23b_clinical_state_on_medication    1327
dtype: int64

In [17]:
df_train_cli.nunique()

visit_id                               2615
patient_id                              248
visit_month                              17
updrs_1                                  32
updrs_2                                  36
updrs_3                                  72
updrs_4                                  19
upd23b_clinical_state_on_medication       2
dtype: int64

In [18]:
df_train_pep.nunique()

visit_id              1113
visit_month             15
patient_id             248
UniProt                227
Peptide                968
PeptideAbundance    738931
dtype: int64

In [19]:
df_train_pro.nunique()

visit_id         1113
visit_month        15
patient_id        248
UniProt           227
NPX            218795
dtype: int64

In [22]:
df_train_cli.visit_month.unique()

array([  0,   3,   6,   9,  12,  18,  24,  30,  36,  42,  48,  54,  60,
        72,  84,  96, 108])

In [20]:
df_train_pep.visit_month.unique()

array([  0,   3,   6,  12,  18,  24,  30,  36,  48,  54,  60,  72,  84,
        96, 108])

In [21]:
df_train_pro.visit_month.unique()

array([  0,   3,   6,  12,  18,  24,  30,  36,  48,  54,  60,  72,  84,
        96, 108])

In [24]:
#what is is cli but not others
[a for a in df_train_cli.visit_month.unique() if a not in df_train_pro.visit_month.unique()]

[9, 42]