# KAGGLE 

https://www.kaggle.com/competitions/amp-parkinsons-disease-progression-prediction

In [1]:
import torch
import os
import pandas as pd
import torch.optim as optim
import sklearn

from sklearn.model_selection import train_test_split

#the following gives access to utils folder
#where utils package stores shared code
import os
import sys
PROJECT_ROOT = os.path.abspath(os.path.join(
                  os.getcwd(),
                 "../")
)

#only add it once
if (PROJECT_ROOT not in sys.path):
    sys.path.append(PROJECT_ROOT)

# Display all cell outputs
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

from IPython import get_ipython
ipython = get_ipython()

# autoreload extension
if 'autoreload' not in ipython.extension_manager.loaded:
    %load_ext autoreload

%autoreload 2

import utils as ut

In [4]:
import utils as ut
ut.setup_packages()
ut.setup_env()
ut.setup_data()

setup data...
Script already ran...bailing


In [3]:
import utils_parkinsons as ut

In [6]:
df_train_cli = pd.read_csv(ut.CFG.DATAP+"train_clinical_data.csv")
df_train_pep = pd.read_csv(ut.CFG.DATAP+"train_peptides.csv")
df_train_pro = pd.read_csv(ut.CFG.DATAP+"train_proteins.csv")

In [12]:
print(f'df_train_cli={df_train_cli.shape}, df_train_pep={df_train_pep.shape},df_train_pro={df_train_pro.shape}') 

df_train_cli=(2615, 8), df_train_pep=(981834, 6),df_train_pro=(232741, 5)


In [15]:
df_train_cli.isnull().sum()

visit_id                                  0
patient_id                                0
visit_month                               0
updrs_1                                   1
updrs_2                                   2
updrs_3                                  25
updrs_4                                1038
upd23b_clinical_state_on_medication    1327
dtype: int64

In [17]:
df_train_cli.nunique()

visit_id                               2615
patient_id                              248
visit_month                              17
updrs_1                                  32
updrs_2                                  36
updrs_3                                  72
updrs_4                                  19
upd23b_clinical_state_on_medication       2
dtype: int64

In [18]:
df_train_pep.nunique()

visit_id              1113
visit_month             15
patient_id             248
UniProt                227
Peptide                968
PeptideAbundance    738931
dtype: int64

In [19]:
df_train_pro.nunique()

visit_id         1113
visit_month        15
patient_id        248
UniProt           227
NPX            218795
dtype: int64

In [22]:
df_train_cli.visit_month.unique()

array([  0,   3,   6,   9,  12,  18,  24,  30,  36,  42,  48,  54,  60,
        72,  84,  96, 108])

In [20]:
df_train_pep.visit_month.unique()

array([  0,   3,   6,  12,  18,  24,  30,  36,  48,  54,  60,  72,  84,
        96, 108])

In [21]:
df_train_pro.visit_month.unique()

array([  0,   3,   6,  12,  18,  24,  30,  36,  48,  54,  60,  72,  84,
        96, 108])

In [24]:
#what is is cli but not others
[a for a in df_train_cli.visit_month.unique() if a not in df_train_pro.visit_month.unique()]

[9, 42]